server:
  port: 20002
# Spring
spring:
  application:
    name: test_service
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:20001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
